name: loading_animation_widget
description: flutter loading animation or spiner whatever you wanna call.
repository: https://github.com/watery-desert/loading_animation_widget



version: 0.0.1-beta.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
