name: loading_animation_widget
description: This package contains loading animation or loading spiner or loader. It's usually used to show loading animation when the app is in loading state or something is processing.
repository: https://github.com/watery-desert/loading_animation_widget



version: 0.0.1-beta.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
